id: c52ec521-9188-4a9e-a4cd-34a3dfbc3d27
name: Unauthorized DHCP configuration in the network (Microsoft Defender for IoT)
description: |
  'This alert leverages Defender for IoT to detect an unauthorized DHCP configuration indicating a possible unauthorized device configuration.'
severity: Medium
requiredDataConnectors:
  - connectorId: IoT
    dataTypes:
      - SecurityAlert (ASC for IoT)
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Impact
relevantTechniques:
  - T0813
query: |
  SecurityAlert
  | where AlertName == "Device Failed to Receive a Dynamic IP Address"
  | extend DeviceId = tostring(parse_json(ExtendedProperties).DeviceId)
  | extend SourceDeviceAddress = tostring(parse_json(ExtendedProperties).SourceDeviceAddress)
  | extend DestDeviceAddress = tostring(parse_json(ExtendedProperties).DestinationDeviceAddress)
  | extend RemediationSteps = tostring(parse_json(RemediationSteps)[0])
  | extend Protocol = tostring(parse_json(ExtendedProperties).Protocol)
  | project
    TimeGenerated,
    DeviceId,
    ProductName,
    ProductComponentName,
    AlertSeverity,
    AlertName,
    Description,
    Protocol,
    SourceDeviceAddress,
    DestDeviceAddress,
    RemediationSteps,
    Tactics,
    AlertLink
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: SourceDeviceAddress
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: DestDeviceAddress
eventGroupingSettings:
  aggregationKind: AlertPerResult
customDetails:
  Sensor: DeviceId
  Protocol: Protocol
alertDetailsOverride:
  alertDisplayNameFormat: (MDIoT) {{AlertName}}
  alertDescriptionFormat: (MDIoT) {{Description}}
  alertTacticsColumnName: Tactics
  alertSeverityColumnName: AlertSeverity
version: 1.0.0
kind: Scheduled
