# Pipeline Policies
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  - group: ES-General
  
jobs:
- job: MigrateLAtoADX
  condition: true
  displayName: 'Migrate LA to ADX'
  steps:
  - task: AzurePowerShell@5
    displayName: 'Migrate LA to ADX'
    inputs:
      azureSubscription: 'Root Management Group'
      ScriptType: 'FilePath'
      ScriptPath: 'Code/Scripts/adx/Migrate-LA-to-ADX.ps1'
      ScriptArguments: '-SecretKey $(ARM_CLIENT_SECRET) -LogAnalyticsSubscriptionId $(LogAnalyticsSubscriptionId) -LogAnalyticsWorkSpaceName $(LogAnalyticsWorkSpaceName) -LogAnalyticsResourceGroup $(LogAnalyticsResourceGroup) -AdxResourceGroup $(AdxResourceGroup) -AdxClusterURL $(AdxClusterURL) -AdxDBName $(AdxDBName) -UserInputTables "$(LAExportTablesToADX)" -CreateDataConnection'
      azurePowerShellVersion: 'LatestVersion'
